# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
Your Code
'''

'\nYour Code\n'

In [10]:
import numpy as np 

a = np.arange(4).reshape(2,2) 

print('list(a)):',list(a))
print('tolist(): ', a.tolist())

list(a)): [array([0, 1]), array([2, 3])]
tolist():  [[0, 1], [2, 3]]


list 一唯轉換 a tolist 二唯轉換

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [ ]:
a = np.random.randint(10, size=6) 

'''
Your Code
'''

[1 1 2 0 1 6]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [31]:
import numpy as np 
a = np.random.randint(10, size=6) 
print(a)
print('ndim: ', a.ndim)#數組的軸（維度）的個數
print('shape: ', a.shape)#數組的維度，是一個整數的元組，表示每個維度中數組的大小。對於有 n 行和 m 列的矩陣，shape 將是 (n,m)。因此，shape 元組的長度就是rank或維度的個數 ndim。
print('size: ', a.size)#數組元素的總數，等於 shape 的元素的乘積。
print('dtype: ', a.dtype)#數組中元素類型
print(len(a))
print('itemsize: ', a.itemsize)#數組中每個元素的字節大小
print(type(a))

[8 0 5 7 2 7]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
6
itemsize:  4
<class 'numpy.ndarray'>


In [32]:
import numpy as np
b = np.random.randint(10, size=(3,4)) 
import numpy as np 
a = np.random.randint(10, size=6) 
print(a)
print('ndim: ', a.ndim)#數組的軸（維度）的個數
print('shape: ', a.shape)#數組的維度，是一個整數的元組，表示每個維度中數組的大小。對於有 n 行和 m 列的矩陣，shape 將是 (n,m)。因此，shape 元組的長度就是rank或維度的個數 ndim。
print('size: ', a.size)#數組元素的總數，等於 shape 的元素的乘積。
print('dtype: ', a.dtype)#數組中元素類型
print(len(b))
print('itemsize: ', a.itemsize)#數組中每個元素的字節大小
print(type(b))

[1 0 2 8 5 6]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
3
itemsize:  4
<class 'numpy.ndarray'>


In [33]:
import numpy as np
b = np.random.randint(10, size=(3,4))
print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print(type(b))
print(len(b))

[[4 8 7 7]
 [9 0 3 2]
 [5 2 3 8]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
<class 'numpy.ndarray'>
3


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


In [35]:
import numpy as np
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print(type(c))
print(len(c))

[[[5 4]
  [2 8]
  [8 2]]

 [[1 2]
  [7 8]
  [0 0]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
<class 'numpy.ndarray'>
2


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [36]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 8, 1, 8, 9, 8]
[7, 8, 1, 8, 9, 8]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [37]:
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))
def tolist(iterable):
    if type(iterable) != np.ndarray:#input不是numpy,input原封不動傳回來
        return iterable
    newlist = []#清楚程式跑到哪裡
    for obj in iterable:#input型態numpy array把array拆開,把每個元素變成input
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 8, 1, 8, 9, 8]
[[4, 8, 7, 7], [9, 0, 3, 2], [5, 2, 3, 8]]
[[[5, 4], [2, 8], [8, 2]], [[1, 2], [7, 8], [0, 0]]]


In [39]:
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 3, 3, 5, 8, 9]
[[5, 9, 1, 5], [1, 6, 4, 8], [7, 3, 0, 6]]
[[[7, 2], [4, 6], [1, 3]], [[9, 0], [9, 2], [8, 1]]]
