# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [8]:
'''
Your Code
'''

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [4]:
import numpy as np 

a= np.array(range(1,12,1))

for x in range (2,6,1):
    a[x] = -a[x]
    
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [31]:
import numpy as np 

a= np.arange(12)
print(a)

a[(a>=2) & (a<7)]*=-1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1 -2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [5]:
A = np.random.rand(3, 6)

'''
Your Code
'''

'\nYour Code\n'

In [38]:
a = np.random.rand(3, 6)
print(a)
print(a[a > 0.5])


[[0.85781024 0.9403057  0.40498745 0.35460719 0.37664644 0.22298387]
 [0.80348138 0.63375231 0.06955748 0.90678682 0.95599561 0.68632053]
 [0.84459218 0.93358797 0.41890868 0.55174186 0.46123825 0.58303826]]
[0.85781024 0.9403057  0.80348138 0.63375231 0.90678682 0.95599561
 0.68632053 0.84459218 0.93358797 0.55174186 0.58303826]


In [24]:
a = np.random.rand(10)
print(a)
b = 0
for i in range(0,a.size):
    if (a[i] > 0.5):
        b+=1
print(b)

[0.056483   0.96955655 0.93711503 0.67329631 0.2498808  0.98834004
 0.20300265 0.90567706 0.59830996 0.28117791]
6


In [34]:
A = np.random.rand(10)

count = 0
print(A)

for x in range(len(A)):
    if A[x] > 0.5:
        count += 1
print(count)

[0.07909942 0.19312033 0.42565168 0.25472205 0.14205876 0.34402889
 0.65903727 0.40799929 0.04077331 0.50082244]
2
