# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



sum() 內建函式, np.sum(),a.sum(),np or array底下

In [ ]:
'''
Your Code
'''

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


正規化(Normalization)？ 就是結構化分析與設計中，建構 「資料模式」所運用的一個技術，其目的是為了降低資料的「重覆性」 與避免「更新異常」的情況發生。 因此，就必須將整個資料表中重複性的資料剔除，否則在關聯表中 會造成新增異常、刪除異常、修改異常的狀況發生。

Normalise 的目的就是把數據所有可能值，按比例或按數式，將其限制在一定範圍內。

重新定義數字範圍，並將資料縮放或位移。
常見的縮放是縮放至0~1或是-1~1。
幾種正規化的方法：
1.scaling to a range
修正資料範圍用，其分布不變。
x'=(x-x.min)/(x.max-x.min)

In [ ]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [38]:
A = np.random.random((5, 5))
print(A)

'''
Your Code
'''
A = (A - A.min()) / (A.max()-A.min())
print(A)

[[0.24668758 0.71116146 0.58367007 0.08628486 0.49944491]
 [0.65190945 0.10491531 0.00147303 0.41075214 0.70469802]
 [0.29555542 0.593332   0.62669453 0.57666935 0.01800989]
 [0.11324756 0.57430225 0.66358347 0.46855419 0.73268477]
 [0.22683829 0.05283234 0.20363375 0.86488152 0.85723158]]
[[0.28400757 0.82196137 0.6743008  0.09822909 0.5767512 ]
 [0.75333567 0.11980688 0.         0.47402719 0.81447541]
 [0.34060631 0.68549125 0.72413174 0.66619256 0.019153  ]
 [0.12945729 0.66345098 0.76685652 0.54097355 0.84688968]
 [0.26101811 0.05948436 0.23414261 1.         0.99113984]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [34]:
import numpy as np
A = np.random.random(10)
print(A)
A[A.argmax()]=-1
print(A)


[0.97483315 0.99913977 0.1279347  0.1481831  0.20408853 0.92278356
 0.85289859 0.60709461 0.88435039 0.47300042]
[ 0.97483315 -1.          0.1279347   0.1481831   0.20408853  0.92278356
  0.85289859  0.60709461  0.88435039  0.47300042]
