# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

1. 請比較對一個 100 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

In [85]:
# 記得先 Import 正確的套件
import numpy as np

In [4]:
import numpy as np
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[9 5 4 ... 9 5 9]
  [0 8 2 ... 0 7 1]
  [9 5 7 ... 9 5 6]
  ...
  [1 0 5 ... 5 4 8]
  [9 1 4 ... 8 7 1]
  [3 1 5 ... 8 9 9]]

 [[1 4 5 ... 2 1 0]
  [7 7 8 ... 1 2 3]
  [6 9 7 ... 6 3 1]
  ...
  [2 0 6 ... 6 9 7]
  [3 6 6 ... 7 7 0]
  [3 4 7 ... 5 6 5]]

 [[6 7 5 ... 5 7 4]
  [3 6 7 ... 0 3 4]
  [6 2 8 ... 6 0 8]
  ...
  [6 7 4 ... 2 5 2]
  [6 9 9 ... 5 9 5]
  [3 6 3 ... 2 3 5]]

 ...

 [[2 0 1 ... 7 9 8]
  [6 7 1 ... 0 5 1]
  [7 6 3 ... 6 3 9]
  ...
  [7 7 3 ... 2 2 8]
  [4 9 7 ... 2 5 7]
  [1 7 7 ... 8 5 6]]

 [[7 7 6 ... 4 4 8]
  [7 7 3 ... 0 6 7]
  [7 0 2 ... 0 2 1]
  ...
  [7 9 5 ... 5 0 7]
  [9 5 7 ... 5 3 7]
  [8 3 3 ... 0 4 8]]

 [[8 2 7 ... 8 6 9]
  [5 2 9 ... 6 3 0]
  [3 7 6 ... 3 2 7]
  ...
  [1 5 6 ... 0 7 9]
  [8 7 2 ... 9 6 9]
  [7 1 7 ... 2 9 7]]]


In [13]:
%timeit -n 10 a = 2

for data in Z:
    for row in data:
        for a in row:
            a+=1

64.3 ns ± 19.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
%timeit -n 10 a = 2

for i in Z.flat:
    i+=1

71.4 ns ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
%timeit -n 10 a = 2

Z += 1

70 ns ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
%timeit -n 10 a = 2

'''
Your Code
'''

for data in Z:
    for row in data:
        for a in row:
            a+=1

71.4 ns ± 24.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%timeit -n 10 a = 2
for data in Z:
    for row in data:
        for a in row:
            a+=1

68.6 ns ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit -n 10 a = 2

for i in Z.flat:
    i+=1

47.1 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit -n 10 a = 2
Z +=1

181 ns ± 286 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [30]:
Z = np.random.randint(0,10,50)
print(Z)


[9 2 4 6 4 5 3 1 0 5 0 5 7 7 0 3 7 0 4 1 4 5 9 3 8 5 5 9 6 2 1 8 7 1 7 5 1
 9 5 9 0 6 0 8 4 2 0 0 8 7]


頻率最高的數值與位置

In [42]:
uni,count = np.unique(Z, return_counts = True)
print(uni,count,sep='\n')


[0 1 2 3 4 5 6 7 8 9]
[8 5 3 3 5 8 3 6 4 5]


In [51]:
print('The most frequence high value:',uni[np.argmax(count)])
print('The number of most frequence high value:',max(count))

The most frequence high value: 0
The number of most frequence high value: 8


In [50]:
counts = np.unique(Z, return_counts=True)
print(uni[np.argmax(count)])
print(max(count))
print(np.where(Z==uni[np.argmax(count)]))

0
8
[ 8 10 14 17 40 42 46 47]


In [52]:
print('The postion of most frequence high value:',np.where(Z==uni[np.argmax(count)])[0])
#np.where()[0] row，np.where()[1]column

The postion of most frequence high value: [ 8 10 14 17 40 42 46 47]


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [53]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[0, 7, 8, 6, 0, 2]
[0, 7, 8, 6, 0, 2]
[[8, 6, 1, 0], [1, 7, 9, 5], [1, 1, 3, 4]]
[array([8, 6, 1, 0]), array([1, 7, 9, 5]), array([1, 1, 3, 4])]
[[[0, 0], [6, 8], [4, 7]], [[8, 0], [3, 3], [5, 6]]]
[array([[0, 0],
       [6, 8],
       [4, 7]]), array([[8, 0],
       [3, 3],
       [5, 6]])]


In [54]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[3, 5, 9, 6, 9, 3]
[3, 5, 9, 6, 9, 3]


In [64]:
print(list(a))

[3, 5, 9, 6, 9, 3]


In [55]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[6, 5, 4, 7], [1, 2, 3, 0], [0, 9, 9, 7]]
[array([6, 5, 4, 7]), array([1, 2, 3, 0]), array([0, 9, 9, 7])]


In [65]:
b_list=[]
for i in b:#0,1,2
    b_list.append(list(i))
    print(b_list)

[[6, 5, 4, 7]]
[[6, 5, 4, 7], [1, 2, 3, 0]]
[[6, 5, 4, 7], [1, 2, 3, 0], [0, 9, 9, 7]]


In [69]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c),)

[[[8, 3], [3, 6], [1, 9]], [[8, 7], [4, 7], [2, 4]]]
[array([[8, 3],
       [3, 6],
       [1, 9]]), array([[8, 7],
       [4, 7],
       [2, 4]])]


In [76]:
all_list=[]
for i in range(c.shape[0]):#一維
    c_list=[]
    for j in range(c.shape[1]):#二維
        c_list.append(list(c[i][j]))
    print(c_list)

[[8, 3], [3, 6], [1, 9]]
[[8, 7], [4, 7], [2, 4]]


In [ ]:
all_list=[]
for i in range(c.shape[0]):#一維
    c_list=[]
    for j in range(c.shape[1]):#二維
        c_list.append(list(c[i][j]))
    c_all_list.append(c_list)

print(all_list)

In [71]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 5, 9, 6, 9, 3]
[[6, 5, 4, 7], [1, 2, 3, 0], [0, 9, 9, 7]]
[[[8, 3], [3, 6], [1, 9]], [[8, 7], [4, 7], [2, 4]]]
